### ISSUE TITLE
関数vec2sqlenがうまく動きません。

### ISSUE THREAD

**Issue by m1goh** [msakuta/rusty-stacker#3]
M1号と申します。Rustで作るプログラミング言語を楽しく読ませていただいています。

P.60の関数vec2sqlenがうまく動かないです。
こんな感じです。Rustのコードは、07-functions.rsを使用しました。

`akiyoshi@BYCYCLE:~/my_rust$ cd rustack071
akiyoshi@BYCYCLE:~/my_rust/rustack071$ cargo run
   Compiling rustack071 v0.1.0 (/home/akiyoshi/my_rust/rustack071)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/rustack071`
/square { dup * } def
stack: []
/vec2sqlen { square exch square exch + }
stack: [Sym("vec2sqlen"), Block([Op("square"), Op("exch"), Op("square"), Op("exch"), Op("+")])]
1 2 vec2sqlen puts
thread 'main' panicked at src/main.rs:165:10:
"vec2sqlen" is not a defined operation
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

こちらの関数を動くようにするにはどうしたらよいでしょうか？教えて下さい。よろしくお願いします。

**Comment by m1goh** [comment]
ファイルに書いて実行したところできました。

`akiyoshi@BYCYCLE:~/my_rust/rustack07$ cargo run -- vec2sqlen.txt
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/rustack07 vec2sqlen.txt`
5
akiyoshi@BYCYCLE:~/my_rust/rustack07$ cat vec2sqlen.txt
/square { dup * } def
/vec2sqlen { square exch square exch + } def
1 2 vec2sqlen putsakiyoshi@BYCYCLE:~/my_rust/rustack07$`

お騒がせしました。<(_ _)>

**Comment by msakuta** [comment]
動いたようで何よりです！

ちなみに、GitHubにコード断片やターミナル出力をコピペするときは、３連バックティック (```) で囲むとレイアウトが崩れずに済みます。

上のコメントは次のような出力になりますかね。

```
akiyoshi@BYCYCLE:~/my_rust/rustack07$ cargo run -- vec2sqlen.txt
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/rustack07 vec2sqlen.txt`
5
```

**Comment by m1goh** [comment]
佐久田さん、返信ありがとうございます。嬉しかったです。

今度、機会があった時は3連バックティックを使ってみます。

**Comment by kuroyasu67** [comment]
書籍（Kindle版）では、`vec2sqlen`の定義は次の通りでした。

```
/vec2sqlen { square exch square exch + }
```

最後に`def`がないため、次の通り入力したら正常な出力を得られました。

```
/vec2sqlen { square exch square exch + } def
```

**Comment by msakuta** [comment]
@xjr1300 ご指摘の通りです。書籍の正誤表に反映しておきます。
